// TO AVOID REUSING THIS CODE TO MAKE NEW VARIABLES EACH TIME:
#ifndef INTRO_H
#define INTRO_H

char intro0[2971] =
"   |v||P||?YYP?YYPYP?PY|PYYYY?Y?YYPPPY|?PYYPPY?PP?||PP?|P?PPPYPYY|PPPYPY|??YY??P?YYP?YY|??YP???YYP??PP?YYPPYYPPYY|Y|PYY?YY??YYPYY|PYP|???PYYYPY|YPP?PY??YP?P?PP??|?\n   Os                                                                                                                                                            Pv\n   My                            fyCP   k$Pc               XeAj                                            bKGpdGGdpBUG     mGqZ   IbKqT     fpOpmbqUBi          bi\n   Oy          LYn   TdgHgROy    ORHI   RHQf              BgQHRI     hWRRBNMBs!                            NDRDQWWQDDRO     QQRX   TgHBT     JHgQivivi<          pi\n   Mz  SZOP   OWHY  DROTicNRWy   qWgT   WBRT             +NHDRWN:    BBBETyeBQM+   MggBOOm$V=                  OHBX         WRBj   YWHRi     FRQQ                Bv\n   Ot  ABHO^ yBRZ   QWN   KQBk   GRBT   HWR}             IHREkWgL    xWW}   eHHn   MBRyyJxmRi                  RQHk         RWROkZ$KQBQv     nQHWQQgRWx          Ui\n   Mz   mRgX=RBM>   WBu   dRgZ   dRWT   HgR{             GHWvvHRb    BHH}   CRQn   MQg?                        DRQw         BHQKzzzkHRRv     jRgg                mv\n   My   *MHgRWQY    QBu   OWWZ   UBQT   HQWL            ?gHO__MWR=   AggAstNOBQv   ORQi                        NWQP         HWQI   TWgRi     JBBHviiiv+          Ov\n   Oz    iRggWI     HHo   OBBX   OBWY   HBBT            IQWRS$ORHy   PRRMURHQOP    MWgNMMAz                    OWHO         gHHA   YHHRI     NHRQHHgQBI          Oi\n   Ot     tHWO=     HBF   dHQB   KQWT   BWBx            DHWZSSBWHm   BW}   RQBi    RQysXPN                     Pvv|         vviY   <vii<     =vviiviiv+          Ki\n   Ot     yWRB      WRV   OQBY   aHgB   BHWb           IHRB    WHW   hBW   YgRm    ORRY                                                                          Oi\n   Ot     yWRB      WRV  YOQBY   aHgBzzBHWb            IHRB    WHWi  hHBT  YgRm^   ORRY                 e ! v                                    yr    cZY       bv\n   Ms     fQWR      NWRDMQQDs     vkONOMXI             VMMj    XHRA  PgBf   OWHc   OHHv                 e F M        PfkkeatfttzIkXVY;          OgRQ   HHf       Gv\n   Mf     fWHH       IoaAfv:                                                }SpK   MQgQOMh$Fr           I I O     iIbt               VOt       xRRRQn IRgt       bv\n   Oz     ?tTv                                                                     =PvTsV$OR            vDgy*   vBB   pRRBWHRQRRgQQDZ  lOZ     <OWWRr eRHs       mv\n   Mf                    ^Itv         +sn=     iaC*                                                      PW   =AO  FHHRgWRWRBgWBgBgBgHO  jRT    _XB+  XQHf       bv\n   Ot                   iNgMv         ogRB    iQWO=                      ;EMA                            xQ   XO  BWRWQWRRgWgHHHHRHQWQBBu TBT    ox   YgRz       mi\n   My                  FBWZ_   _r>    +UWH   TNBO<                       XQRi                            PW  lB  XBBWgBQWRQQgRRWWgBHBWBRRx wRd   JS   ISgf       bs\n";
char intro1[2970] =
"   Mf  QOMhMQgQOMh    IHRB    dNgR    fMHT  MQMi>ICz<      <i}}v?ou  -=sBWZrCV=   MQgQOMhMQgQO           SW  BH  QRHRHBBQWWBWHgHBHRQHQQRRG }HY   oS    iHz       Bv\n   Oy                =RRO<   SRBWy   ^dWt  TBNIEZXHRy    fOBRVFkQHN     Rqe                              wQ  Pg  NBHBRQQBBHRWRQBRWRBRHgRHd }RT   Fw    iHy       qv\n   Mf                zHHz   iRgk=   YMHT  YRgR  ,bRw   >OgMx  *MQO>   PHQ;                               wR  cgs oHQRRgHQBBRRgBQQQWWWggRgP OW+   uS    iBs       Oi\n   Mt  QOMhMQgQOMh   sRBr  ^nHHY  >VHMP  ZBRy:  QM=   AWN+   DWB;   {HgT          MQgQOMhMQgQO           hR   Zgi $HgRgHRQRBRBQQQRWQHBBBl IBY    $m    vWf       Ui\n   My                {RWPC$RSoWgMBgNn:  vWBI   OQdT  EORDyfxI$gP{lYXURWacInAi                            PR   =ENs  OHHBWHHHRgRRHWRWRRxr ZOI     RWr   vRz       Bv\n   Ot                 >IFy{r  +LTI=     rxi    =i}x{l>!       Tx{?> <iLx                                 hQ     vKMI  VMHRBHRgWWRRBBt?= OS;      ggP   iHt       mi\n   Mf                                                                                                    EM       i$N$               BMN=        HWP   iHs       qv\n   Ot                                                                                                    Ju          YzXpqUaXXEkbmmII;           TN    =C}       qi\n   Oy  RQQM,   PRRHR*  =FGWgWBNZv     hWBRY   $HQgI        gWHgBWBQQQ$      YgBQWR*   iWQgHODDgWWg$                                                              bv\n   Oz  fWHHX   OggRP  iQQWOaubQHBA!   hHRWP   XBBHL        gRRMBBEEAwf      PgQQgQa   PBhPOBWBpSxPC   xYxP|<,                                                    Uv\n   Of  ^kHQN| sgHBz   OHBB_   GQQHr   PQBgP   CWRQv        WWRj            >gBRNHQO,      vgRBi       hHgWQRgO$;   +jMWgHHmT   iPRQBWOS=  zzu    BS$+ ZSusi|six  bv\n   My   +OWWM|NHgX    OWQU!   qBRg*   wHgWP   FgWgv        RQQj            zQBH HgBc      iQBRT       BWRI;vYRQD  YRHGlvTgHQP SBBXiv$QBG  RBQ    QRM, BRgNQWRWR  qi\n   Mt    ?DHgWRRm,    ORQG^   BQQW;   AWgH?   FgBgi        HRWA;PviY       NQWZ  Bgw      vQgWY       wQgv   IWH  BWQ}   HQgT HBR   YBQO  WgQ    gHG  gRg        Uv\n   Of     lRBQBOr     Oggd!   mRQgr   EgQBP   jHWgv        RQRQgRWQN      iQBWT  RBQ>     vRQBT       wWWy   pRQ  AHBT   WBWi WHQ         RWH    gRG  QBH        mv\n   Mt      kggWT      OBRp,   bBHW=   hBRW|   FQWBi        gWWhfsztY      XWBN   RHRt     iQQBY       BWRBQgBNC   ERBx   HWBv BWW  zyti   Qgg    QgO  HgBROOET   bi\n   Ot      FWBHY      MHHO,   UgQR*   xRBHP   FgRHv        BBWN          *NHQWONDgRRO     iRgQY       PgRY=TRH    hBH}   HRBv QRR  ANBWS  HRW    BBp  gBgTyEPy   Ov\n   Os      nWRRT      ORHd:   dQWQ*   AQBHY   yBQWv        HQgu          zRBQPkS$MRRRi    vHHQY       ERgv  PgHA  PQgL   BBRv WBQ   YRWZ  QQH   {BQp  BQg        bi\n   Mz      CQRgI      oHRWZliyRggR+   IWQHAliyDRHN=        BHQZvvilxcv  !PggRr   YRBQZ    vQBRf       wBBc  >gQBr SRgY  |gQW  gQWP>*ZRWA  HHgtv{OQgX  WRB$fTvi   qi\n";

char intro2[493] =
"   Ot      FBRgI       cdRBgHBWDS>     vPgBHQRWBSr         BQgWBHRgRQ$  PgWHp    <RWQO>   iHRQj       ltIi   NORP TRHQOMHWM}  JRgBQRQMt^  rXDHHWOA{   nEPmMQRQg  Uv\n   Oz                                                                                                                                                            Bv\n   OC=YYPPYYPivvvivvi|YYY|?YYP?|Y?vviiiivivivPYP?viiiiiiviviviviiYPY|vvviviviiiivviviPY?PP?PY|PYP|P?YYP|PPY??|Y|PY?P?P|PY|YYPPPYPPY|Y?YY?YPY?P||P|YPY|||?|PPYYPP?CO";

#endif // TO END THE DEFINITION FUNCTION TO ONE TIME USE ONLY!
